steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=gke.yaml
  - --cluster=gcp-devops-project
  - --location=us-central1-c
  - --namespace=gke-devops-prod
  - --image=gcr.io/$PROJECT_ID/gcpdevops:$SHORT_SHA
