apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
spec:
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: myapp
        image: myapp
        ports:
        - containerPort: 8080
