apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: myapp
        image: gcr.io/grafana-demo-project/gcpdevops-dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gke-app-service
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

